name: patrol_test
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_driver:
    sdk: flutter
  test: any


  # external
  injectable: 2.1.0
  get_it: 7.2.0


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter



  # external
  build_runner: 2.3.3
  injectable_generator: 2.1.3
  mockito: 5.4.0
  path_provider: 2.0.12
  flutter_native_splash: 2.2.16
  flutter_launcher_icons: 0.11.0

  flutter_lints: 2.0.1

  patrol: ^2.0.1

patrol:
  app_name: 'Patrol test'
  android:
    package_name: com.example.test.patrol_test

flutter:

  uses-material-design: true

